name: IP scraper

on:
  # push:
  #   branches:
  #     - main
  schedule:
    - cron: "*/2 * * * *" 

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get working copy
        uses: actions/checkout@master
        with:
          fetch-depth: 1

      - name: Set up Python 3.8                               
        uses: actions/setup-python@v2                               
        with:                                 
          python-version: '3.8'

      - name: Dependencies install 
        run: pip install requests

      - name: Update README
        run: |
          python scrape_84xo.py

      - name: Deploy
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git add .
          git commit -am "VISCA BARCA"
          git push --all -f https://${{ secrets.REPO_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git
